[package]
name = "clr_lite"
version = "0.1.0"
authors = ["Leo Battle <leowbattle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binary_reader = { path = "../binary_reader" }
bitflags = "1.2.1"